server:
  port: 20001

spring:
  application:
    name: service-producer
  redis:
    host: 10.0.8.250
    port: 6379
    password: jkfq2016
    #Redis数据库索引（默认为0）
    database: 5
    # 连接超时时间（毫秒）
    timeout: 3000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 0

eureka:
  client:
    service-url:
      #\u8BBE\u7F6E\u4E0EEureka Server\u4EA4\u4E92\u7684\u5730\u5740\uFF0C\u67E5\u8BE2\u670D\u52A1\u548C\u6CE8\u518C\u670D\u52A1\u90FD\u9700\u8981\u4F9D\u8D56\u8FD9\u4E2A\u5730\u5740\u3002\u9ED8\u8BA4\u662Fhttp://localhost:8761/eureka \uFF1B\u591A\u4E2A\u5730\u5740\u53EF\u4F7F\u7528 , \u5206\u9694\u3002
      defaultZone: http://10.0.8.52:8001/eureka/


logging:
  level:
    org.springframework.security: DEBUG


security:
  oauth2:
    resource:
      jwt:
        key-url: http://10.0.8.52:60002/uaa/oauth/token_key
      user-info-uri: http://10.0.8.52:60002/uaa/oauth/user
      #是否使用token info，默认为true
      prefer-token-info: true

